name: Testing

env:
  VITE_API_URL: ${{ vars.VITE_API_URL }}

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Git checkout
        uses: actions/checkout@v4

      - name: 💾 Install modules
        run: npm ci

      - name: 🧪 Testing
        run: npm test
